# Generated by Django 3.2.13 on 2024-01-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('link', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=512)),
                ('distance', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('img', models.CharField(max_length=1024)),
                ('price', models.CharField(max_length=30)),
                ('date_from', models.CharField(max_length=30)),
                ('date_to', models.CharField(max_length=30)),
            ],
        ),
    ]
