# Generated by Django 3.2.13 on 2024-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='img',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='link',
            field=models.CharField(max_length=3000),
        ),
    ]
