# Generated by Django 3.2 on 2024-04-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240106_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_to',
        ),
        migrations.AddField(
            model_name='booking',
            name='occupancy',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='AvailableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=30)),
                ('date_to', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
    ]
