# Generated by Django 3.2 on 2024-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240429_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebooking',
            name='created',
            field=models.DateField(default='2024-04-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablebooking',
            name='updated',
            field=models.DateField(default='2024-04-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateField(default='2024-04-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateField(default='2024-04-29'),
            preserve_default=False,
        ),
    ]
