# Generated by Django 3.2 on 2024-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240429_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebooking',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availablebooking',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
