# Generated by Django 3.2 on 2024-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240429_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='availablebooking',
            name='price',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
