# Generated by Django 3.2 on 2024-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240429_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField()),
                ('occupancy', models.CharField(default=2, max_length=30)),
                ('start', models.CharField(default=4, max_length=30)),
            ],
        ),
    ]
