# Generated by Django 3.2 on 2024-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_processactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactive',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
