# Generated by Django 3.2 on 2024-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_processactive_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebooking',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
