# Generated by Django 3.2 on 2024-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_availablebooking_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebooking',
            name='total_search',
            field=models.IntegerField(default=0),
        ),
    ]
