# Generated by Django 3.2 on 2024-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_availablebooking_total_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactive',
            name='position',
            field=models.JSONField(default={}),
        ),
    ]
