# Generated by Django 3.2 on 2024-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_processactive_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebooking',
            name='currenct',
            field=models.BooleanField(default=False),
        ),
    ]
