# Generated by Django 3.2 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240620_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactive',
            name='time_sleep_minutes',
            field=models.IntegerField(default=1),
        ),
    ]
