# Generated by Django 3.2 on 2024-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_processactive_time_sleep_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='https://www.booking.com')),
                ('city_and_country', models.TextField(default='Madrid, Comunidad de Madrid, España')),
            ],
        ),
    ]
