# Generated by Django 3.2 on 2024-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_generalsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processactive',
            name='time_sleep_minutes',
        ),
        migrations.AddField(
            model_name='generalsearch',
            name='time_sleep_minutes',
            field=models.IntegerField(default=1),
        ),
    ]
