# Generated by Django 3.2 on 2024-08-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20240724_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailSuitesFeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_avail', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CantAvailSuitesFeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avail', models.CharField(max_length=5)),
                ('avail', models.IntegerField(default=0)),
                ('avail_suites_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availsuitesferia')),
            ],
        ),
    ]
