# Generated by Django 3.2 on 2024-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240806_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebooking',
            name='start',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
