# Generated by Django 3.2 on 2024-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_availablebooking_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=30)),
                ('occupancy', models.IntegerField(choices=[('2 Personas', 2), ('3 Personas', 3), ('5 Personas', 5)], default=2)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MessageByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=30)),
                ('occupancy', models.IntegerField(choices=[('2 Personas', 2), ('3 Personas', 3), ('5 Personas', 5)], default=2)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=30)),
                ('occupancy', models.IntegerField(choices=[('2 Personas', 2), ('3 Personas', 3), ('5 Personas', 5)], default=2)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
