# Generated by Django 3.2 on 2024-08-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_temporadabyday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporadabyday',
            old_name='numer',
            new_name='number',
        ),
    ]
