# Generated by Django 3.2 on 2024-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_numer_temporadabyday_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadabyday',
            name='bg_color',
            field=models.TextField(choices=[('bg-danger', 'bg-danger'), ('bg-warning', 'bg-warning'), ('bg-success', 'bg-success'), ('bg-secondary', 'bg-secondary'), ('bg-dark', 'bg-dark')], default='bg-success'),
        ),
    ]
