# Generated by Django 3.2 on 2024-08-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_temporadabyday_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_search', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=4)),
                ('start', models.CharField(max_length=20)),
                ('date_from', models.CharField(max_length=30)),
                ('date_to', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='availablebooking',
            name='complement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.complement'),
        ),
    ]
