# Generated by Django 3.2 on 2024-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_availwithdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complement',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complement',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
