# Generated by Django 3.2 on 2024-11-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_copypricewithday_pricewithnamehotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyPriceWithDaySF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('avail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cantavailsuitesferia')),
            ],
        ),
    ]
