# Generated by Django 3.2 on 2024-11-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_copypricewithdaysf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copypricewithdaysf',
            name='avail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availsuitesferia'),
        ),
    ]
