# Generated by Django 3.2 on 2024-11-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_copypricewithdaysf_avail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CopyPriceWithDaySF',
            new_name='CopyPriceWithNameFromDay',
        ),
        migrations.AlterField(
            model_name='copypricewithnamefromday',
            name='avail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pricewithnamehotel'),
        ),
        migrations.CreateModel(
            name='CopyAvailWithDaySF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avail', models.CharField(max_length=5)),
                ('avail', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('avail_suites_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availsuitesferia')),
            ],
        ),
    ]
