# Generated by Django 3.2 on 2024-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20241125_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadabyday',
            name='bg_color',
            field=models.TextField(choices=[('bg-danger', 'bg-danger'), ('bg-info', 'bg-info'), ('bg-warning', 'bg-warning'), ('bg-success', 'bg-success'), ('bg-secondary', 'bg-secondary'), ('bg-dark', 'bg-dark')], default='bg-success'),
        ),
    ]
