# Generated by Django 3.2 on 2024-11-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_processactive_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactive',
            name='type_proces',
            field=models.IntegerField(choices=[(1, 'City'), (2, 'Name')], default=1),
        ),
        migrations.AlterField(
            model_name='processactive',
            name='occupancy',
            field=models.CharField(default=2, max_length=30),
        ),
    ]
