# Generated by Django 3.2 on 2024-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_generalsearch_proces_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copyavailwithdaysf',
            old_name='avail',
            new_name='avail_1',
        ),
        migrations.AddField(
            model_name='copyavailwithdaysf',
            name='avail_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copyavailwithdaysf',
            name='avail_4',
            field=models.IntegerField(default=0),
        ),
    ]
