# Generated by Django 3.2 on 2024-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20241127_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyavailwithdaysf',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='copypricewithday',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='copypricewithnamefromday',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
