# Generated by Django 3.2 on 2024-12-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20241127_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricewithnamehotel',
            name='occupancy',
            field=models.IntegerField(default=2),
        ),
    ]
