# Generated by Django 3.2 on 2024-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_pricewithnamehotel_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyavailwithdaysf',
            name='avail_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporadabyday',
            name='bg_color',
            field=models.TextField(choices=[('bg-danger', 'bg-danger'), ('bg-danger', 'bg-danger'), ('bg-warning', 'bg-warning'), ('bg-success', 'bg-success'), ('bg-secondary', 'bg-secondary'), ('bg-dark', 'bg-dark')], default='bg-success'),
        ),
    ]
