# Generated by Django 3.2 on 2024-12-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20241212_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyComplementWithDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_search', models.CharField(max_length=30)),
                ('created', models.DateField(blank=True, null=True)),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complement')),
            ],
        ),
    ]
