# Generated by Django 3.2 on 2025-01-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_copycomplementwithday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialPlataform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataform_option', models.TextField(choices=[('suitesferia', 'suitesferia'), ('roomprice', 'roomprice')], default='suitesferia')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
