# Generated by Django 3.2 on 2025-01-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_credentialplataform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='occupancy',
            field=models.IntegerField(choices=[(1, '1 Personas'), (2, '2 Personas'), (3, '3 Personas'), (4, '4 Personas'), (5, '5 Personas'), (6, '6 Personas')], default=2),
        ),
    ]
