# Generated by Django 3.2 on 2025-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_price_occupancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('current_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
