# Generated by Django 3.2 on 2025-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_cronactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataform_option', models.TextField(choices=[('suitesferia', 'suitesferia'), ('roomprice', 'roomprice'), ('booking', 'booking')], default='booking')),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
