# Generated by Django 3.2 on 2025-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='plataform_sync',
            field=models.BooleanField(default=True),
        ),
    ]
