# Generated by Django 3.2 on 2025-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_price_plataform_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='plataform_sync',
            field=models.BooleanField(default=False),
        ),
    ]
