# Generated by Django 3.2 on 2025-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_price_plataform_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadabyday',
            name='bg_color',
            field=models.TextField(choices=[('bg-danger', 'bg-danger'), ('bg-danger', 'bg-danger'), ('bg-warning', 'bg-warning'), ('bg-success', 'bg-success'), ('bg-info', 'bg-info'), ('bg-dark', 'bg-dark')], default='bg-success'),
        ),
    ]
