# Generated by Django 3.2 on 2025-03-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_temporadabyday_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactive',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
