# Generated by Django 4.2.20 on 2025-04-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_botlog_plataform_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('bot_auto', 'bot_auto'), ('bot_default', 'bot_default')], default='bot_default')),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=22)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('time_sleep', models.FloatField(default=0.5)),
                ('time_execute', models.FloatField(default=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='processactive',
            name='active',
        ),
        migrations.RemoveField(
            model_name='processactive',
            name='currenct',
        ),
        migrations.RemoveField(
            model_name='processactive',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='processactive',
            name='date_from',
        ),
        migrations.CreateModel(
            name='BotRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField()),
                ('bot_automatization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.botsetting')),
            ],
        ),
        migrations.CreateModel(
            name='BotAutomatization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('currenct', models.BooleanField(default=False)),
                ('automatic', models.BooleanField(default=False)),
                ('bot_auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_auto', to='app.botsetting')),
                ('bot_default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_default', to='app.botsetting')),
            ],
        ),
    ]
