# Generated by Django 4.2.20 on 2025-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_botrange_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrange',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
