# Generated by Django 4.2.20 on 2025-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_botrange_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsearch',
            name='city_and_country',
            field=models.TextField(default='Madrid, España'),
        ),
        migrations.AlterField(
            model_name='generalsearch',
            name='url',
            field=models.TextField(default='https://www.booking.com/searchresults.es.html?'),
        ),
    ]
