# Generated by Django 4.2.20 on 2025-04-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_generalsearch_city_and_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botrange',
            old_name='bot_automatization',
            new_name='bot_setting',
        ),
    ]
