# Generated by Django 4.2.20 on 2025-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_botsetting_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botsetting',
            old_name='number',
            new_name='number_end',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='number_from',
            field=models.IntegerField(default=1),
        ),
    ]
