# Generated by Django 4.2.20 on 2025-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_rename_number_botsetting_number_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrange',
            name='days',
            field=models.IntegerField(default=30),
        ),
    ]
