# Generated by Django 4.2.20 on 2025-04-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_botrange_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
