# Generated by Django 4.2.20 on 2025-04-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_price_created_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complement',
            name='created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complement',
            name='updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventbyday',
            name='created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventbyday',
            name='updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messagebyday',
            name='created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messagebyday',
            name='updated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
