# Generated by Django 4.2.20 on 2025-04-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_botlog_created_alter_botlog_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='capturas/')),
            ],
        ),
    ]
