# Generated by Django 4.2.20 on 2025-04-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_screenshotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotlog',
            name='created',
            field=models.CharField(default='', max_length=128),
        ),
    ]
