# Generated by Django 4.2.20 on 2025-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_screenshotlog_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_from', models.TimeField(blank=True, null=True)),
                ('hour_to', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='botrange',
            name='hour_range',
            field=models.ManyToManyField(blank=True, null=True, to='app.hourrange'),
        ),
    ]
