# Generated by Django 4.2.20 on 2025-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_hourrange_botrange_hour_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrange',
            name='days_from',
            field=models.IntegerField(default=1),
        ),
    ]
