# Generated by Django 4.2.20 on 2025-04-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_botrange_days_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='botrange',
            name='day_name',
            field=models.ManyToManyField(blank=True, null=True, to='app.day'),
        ),
    ]
