# Generated by Django 4.2.20 on 2025-04-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_day_botrange_day_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bg_color', models.TextField(choices=[('#90EE90', 'verde'), ('#FF0000', 'rojo'), ('#FFD700', 'amarillo'), ('#7FD7FF', 'azul-claro'), ('#63C5F9', 'azul-oscuro')], default='rojo')),
                ('text_color', models.TextField(choices=[('text-success', 'text-success'), ('text-warning', 'text-warning'), ('text-info', 'text-info'), ('text-secondary', 'text-secondary'), ('text-dark', 'text-dark'), ('text-white', 'text-white'), ('text-black', 'text-black'), ('text-primary', 'text-primary')], default='text-white')),
                ('occupancy', models.IntegerField(choices=[(2, '2 Personas'), (3, '3 Personas'), (5, '5 Personas')], default=2)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='messagebyday',
            name='text_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.messagename'),
        ),
    ]
