# Generated by Django 4.2.20 on 2025-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_messagename_messagebyday_text_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagename',
            name='bg_color',
            field=models.TextField(choices=[('#90EE90', 'verde'), ('#FF0000', 'rojo'), ('#FFD700', 'amarillo'), ('#6cb7fc', 'azul-claro'), ('#4a769f', 'azul-oscuro')], default='rojo'),
        ),
    ]
