# Generated by Django 4.2.20 on 2025-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_messagename_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagename',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
