# Generated by Django 3.2 on 2025-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_messagename_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotlog',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
