# Generated by Django 3.2 on 2025-05-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_emailsend_emailsmtp_messageemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecute',
            name='minute_notify',
            field=models.IntegerField(default=30),
        ),
    ]
