# Generated by Django 3.2 on 2025-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_taskexecute_minute_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='active_sync',
            field=models.BooleanField(default=False),
        ),
    ]
