# Generated by Django 3.2 on 2025-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_cookieurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagename',
            name='bg_color',
            field=models.TextField(choices=[('#90EE90', 'verde'), ('#FF0000', 'rojo'), ('#fb6340', 'naranja'), ('#6cb7fc', 'azul-claro'), ('#317ec6', 'azul-oscuro')], default='rojo'),
        ),
        migrations.AlterField(
            model_name='temporadabyday',
            name='bg_color',
            field=models.TextField(choices=[('#f5365c', 'bg-danger'), ('#f5365c', 'bg-danger'), ('#fb6340', 'bg-warning'), ('#8392ab', 'bg-secondary'), ('#11cdef', 'bg-info'), ('#317ec6', 'bg-dark')], default='bg-success'),
        ),
    ]
