# Generated by Django 3.2 on 2025-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20250625_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialplataform',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
