# Generated by Django 4.2.23 on 2025-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_credentialplataform_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsearch',
            name='code',
            field=models.TextField(choices=[('ZEN', 'ZEN'), ('OSU', 'OSU'), ('ILU', 'ILU'), ('ECO', 'ECO'), ('SIL', 'SIL'), ('EXE', 'EXE'), ('SER', 'SER'), ('AXO', 'AXO'), ('DWO', 'DWO'), ('BOS', 'BOS'), ('SEN', 'SEN'), ('TOR2', 'TOR2')], default='ZEN'),
        ),
        migrations.AlterField(
            model_name='price',
            name='occupancy',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Matrimonial'), (2, 'Doble'), (3, 'Triple'), (4, '4 Personas'), (5, 'Suites'), (6, '6 Personas')], default=2),
        ),
    ]
