# Generated by Django 3.2.24 on 2025-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_generalsearch_code_alter_price_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='prev_price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalsearch',
            name='code',
            field=models.TextField(choices=[('ZEN', 'ZEN'), ('OSU', 'OSU'), ('ILU', 'ILU'), ('ECO', 'ECO'), ('SIL', 'SIL'), ('EXE', 'EXE'), ('SER', 'SER'), ('AXO', 'AXO'), ('DWO', 'DWO'), ('BOS', 'BOS'), ('SEN', 'SEN'), ('TOR2', 'TOR2'), ('SF', 'SF')], default='ZEN'),
        ),
    ]
