# Generated by Django 3.2.24 on 2025-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20250902_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cookies', models.JSONField()),
                ('updated_at', models.CharField(max_length=64)),
            ],
        ),
    ]
