# Generated by Django 3.2.24 on 2025-09-19 04:22

import app.now_date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_cookiestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEdgeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de verificación D-EDGE', max_length=20)),
                ('created_at', models.DateTimeField(default=app.now_date.now)),
            ],
            options={
                'db_table': 'dedge_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
